# SonarQube Project Configuration
sonar.projectKey=placement-syndicate
sonar.projectName=Placement Syndicate - DevSecOps
sonar.projectVersion=1.0

# Path to source directories
sonar.sources=user-service/src/main,frontend/src,api-gatway/src,discovery-service/src

# Path to test directories
sonar.tests=user-service/src/test

# Language
sonar.language=java,js

# Encoding
sonar.sourceEncoding=UTF-8

# Exclude node_modules and target folders
sonar.exclusions=**/node_modules/**,**/target/**,**/dist/**

# Quality Gates
sonar.qualitygate.wait=true
