spring.application.name=API-GATEWAY

server.port=8200

spring.cloud.gateway.routes[0].id = user-service
spring.cloud.gateway.routes[0].uri = lb://USER-SERVICE
spring.cloud.gateway.routes[0].predicates[0] = Path=/api/users/**

spring.cloud.gateway.routes[1].id = experience-service
spring.cloud.gateway.routes[1].uri = lb://experience-service
spring.cloud.gateway.routes[1].predicates[0] = Path=/api/experience/**

eureka.client.service-url.defaultZone=http://discovery-service:8100/eureka

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://keycloak:8080/realms/mini-project/protocol/openid-connect/certs

logging.level.org.springframework.cloud.gateway=TRACE

management.endpoints.web.exposure.include=*
management.endpoint.prometheus.enabled=true
management.endpoint.health.show-details=always
